"""initial migration

Revision ID: 020aad570502
Revises: 
Create Date: 2024-05-10 04:27:58.204157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020aad570502'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('redFlagRecords')
    op.drop_table('interventionRecords')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_passport_no', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(), nullable=False))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('role')
        batch_op.drop_column('id_passport_no')

    op.create_table('interventionRecords',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"interventionRecords_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=600), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('media', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='interventionRecords_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='interventionRecords_pkey')
    )
    op.create_table('redFlagRecords',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"redFlagRecords_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=600), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('media', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='redFlagRecords_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='redFlagRecords_pkey')
    )
    # ### end Alembic commands ###
