"""removed resolution tables entirely

Revision ID: 22351f67f00e
Revises: 16e00fc92cdc
Create Date: 2024-05-23 13:24:23.859420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22351f67f00e'
down_revision = '16e00fc92cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corruption_resolutions')
    op.drop_table('petition_resolutions')
    with op.batch_alter_table('corruption_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_comments', sa.String(), nullable=True))

    with op.batch_alter_table('public_petitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_comments', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_petitions', schema=None) as batch_op:
        batch_op.drop_column('admin_comments')

    with op.batch_alter_table('corruption_reports', schema=None) as batch_op:
        batch_op.drop_column('admin_comments')

    op.create_table('petition_resolutions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('justification', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('additional_comments', sa.VARCHAR(length=600), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['public_petitions.id'], name='petition_resolutions_record_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='petition_resolutions_pkey')
    )
    op.create_table('corruption_resolutions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('justification', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('additional_comments', sa.VARCHAR(length=600), autoincrement=False, nullable=True),
    sa.Column('record_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['record_id'], ['corruption_reports.id'], name='corruption_resolutions_record_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='corruption_resolutions_pkey')
    )
    # ### end Alembic commands ###
