"""app

Revision ID: 3bf89234c228
Revises: dd7575c2b629
Create Date: 2024-05-15 15:11:56.658636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf89234c228'
down_revision = 'dd7575c2b629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_reports')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('password_hash')

    op.create_table('incident_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('govt_agency', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('county', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('additional_location_info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('incident_title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('incident_description', sa.VARCHAR(length=600), autoincrement=False, nullable=False),
    sa.Column('media', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='incident_reports_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='incident_reports_pkey')
    )
    # ### end Alembic commands ###
