"""initial migration

Revision ID: 4e031314e11a
Revises: 
Create Date: 2024-05-17 05:53:01.903979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e031314e11a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corruption_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.drop_column('location_url')

    with op.batch_alter_table('public_petitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.drop_column('location_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_petitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_url', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('corruption_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_url', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('latitude')
        batch_op.drop_column('longitude')

    # ### end Alembic commands ###
