"""removed not null constraint on ispassport column in users

Revision ID: 8e99acd57506
Revises: 22351f67f00e
Create Date: 2024-05-27 13:23:01.056232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e99acd57506'
down_revision = '22351f67f00e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id_passport_no',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('id_passport_no',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
