"""removed location_url

Revision ID: 9c295a3642c8
Revises: 4b9370e1d6c0
Create Date: 2024-05-17 15:56:15.024369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c295a3642c8'
down_revision = '4b9370e1d6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_petitions', schema=None) as batch_op:
        batch_op.drop_column('location_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('public_petitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_url', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
